/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_2;
import java.awt.Color;
import java.awt.Graphics;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.DecimalFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author raedk
 */
public class Front extends javax.swing.JFrame {

    /**
     * Creates new form Front
     */
    public Front() {
        initComponents();
    }  
  Neural_Networks nn=new Neural_Networks();
  DecimalFormat d=new DecimalFormat("#.####");
  ImageIcon icon=new ImageIcon();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b5 = new javax.swing.JRadioButton();
        b6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel2.setBackground(new java.awt.Color(102, 153, 255));
        panel2.setForeground(new java.awt.Color(0, 0, 0));

        b1.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 51));
        b1.setText("AND");
        b1.setFocusPainted(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(b3);
        b3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 51));
        b3.setText("NAND");
        b3.setFocusPainted(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(b2);
        b2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 51));
        b2.setText("OR");
        b2.setFocusPainted(false);

        b4.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(b4);
        b4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 51));
        b4.setText("NOR");
        b4.setFocusPainted(false);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Perceptron");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Multilayer");

        b5.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(b5);
        b5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 0, 51));
        b5.setText("XOR");
        b5.setFocusPainted(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(b6);
        b6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 0, 51));
        b6.setText("XNOR");
        b6.setFocusPainted(false);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Max Num of Epoch:");

        t1.setBackground(new java.awt.Color(102, 153, 255));
        t1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(0, 0, 51));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setText("Test");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t3.setBackground(new java.awt.Color(102, 153, 255));
        t3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(0, 0, 51));
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("X2:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Y:");

        t4.setBackground(new java.awt.Color(102, 153, 255));
        t4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        t4.setForeground(new java.awt.Color(0, 0, 51));
        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t5.setEditable(false);
        t5.setBackground(new java.awt.Color(102, 153, 255));
        t5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        t5.setForeground(new java.awt.Color(0, 0, 51));
        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Learning Rate:");

        t2.setBackground(new java.awt.Color(102, 153, 255));
        t2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(0, 0, 51));
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 51));
        jButton3.setText("Learn");
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Best MSE :");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Best Epoch :");

        l1.setBackground(new java.awt.Color(51, 153, 255));
        l1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 0, 51));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l2.setBackground(new java.awt.Color(51, 153, 255));
        l2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 0, 51));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Neural Networks");

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1, 190));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nn.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/mn.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/per.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/table.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("X1:");

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(512, 512));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setForeground(new java.awt.Color(238, 238, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(8, 8, 8))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel2Layout.createSequentialGroup()
                                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(panel2Layout.createSequentialGroup()
                                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                                        .addComponent(b3)
                                                        .addGap(25, 25, 25)
                                                        .addComponent(b4))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                                        .addComponent(b1)
                                                        .addGap(35, 35, 35)
                                                        .addComponent(b2)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel12)
                                            .addComponent(b5)
                                            .addComponent(b6)))
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1))
                                            .addGroup(panel2Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b1)
                                    .addComponent(b2))
                                .addGap(18, 18, 18)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b3)
                                    .addComponent(b4)))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b5)
                                .addGap(18, 18, 18)
                                .addComponent(b6))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(27, 27, 27)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jButton1))
                        .addGap(13, 13, 13)))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel14))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          double y;
          double X;
          ////////////////////Test For Peceptron
        if(b1.isSelected()||b2.isSelected()||b3.isSelected()||b4.isSelected()){  
            int x1=Integer.parseInt(t3.getText());
            int x2=Integer.parseInt(t4.getText());
            X=Double.parseDouble(d.format((x1*nn.w1)+(x2*nn.w2)+(nn.threshold)));
            y=nn.step_function(X);
            t5.setText((int)y+" ");}
           ///////////////////Test For Multilayer
         if(b5.isSelected()||b6.isSelected()){  
           int x1=Integer.parseInt(t3.getText());
            int x2=Integer.parseInt(t4.getText());
           nn.XY3=Double.parseDouble(d.format(x1*nn.w11+x2*nn.w21-nn.threshold3));
           nn.XY4=Double.parseDouble(d.format(x1*nn.w12+x2*nn.w22-nn.threshold4));
           nn.Ya3=Double.parseDouble(d.format(nn.Sigmoid_function(nn.XY3)));
           nn.Ya4=Double.parseDouble(d.format(nn.Sigmoid_function(nn.XY4)));
           nn.XY5=Double.parseDouble(d.format(nn.Ya3*nn.w3+nn.Ya4*nn.w4-nn.threshold5));
           nn.Ya5=Double.parseDouble(d.format(nn.Sigmoid_function(nn.XY5)));
           t5.setText(nn.Ya5+" ");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       File myObj = new File(""); 
       int matlogic[][]=new int[4][3];
       ///////////////////Select file
       if(b1.isSelected()){ 
        myObj = new File("and.txt");
        }
          
        if(b2.isSelected()){
        myObj = new File("or.txt");
        
        }
           
        if(b3.isSelected()){
        myObj = new File("nand.txt");   
        }
           
        if(b4.isSelected()){
        myObj = new File("nor.txt");   
        }
           
        if(b5.isSelected()){
        myObj = new File("xor.txt");   
     }
            
        if(b6.isSelected()){
        myObj = new File("xnor.txt");  
    }
        ///////////////////Read from file and store in matrix
         try {
      
      Scanner myReader = new Scanner(myObj);
      while (myReader.hasNextLine()) {
            for(int i=0;i<4;i++)
            for(int j=0;j<3;j++)
        matlogic[i][j] = myReader.nextInt();
       
      }
      myReader.close();
    } catch (FileNotFoundException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }double bmse=1;
            double bepoch=0;
            //////////print matrix as a truth table
           for(int i=0;i<4;i++){
          for(int j=0;j<3;j++){
      System.out.print( matlogic[i][j]);
       System.out.print(" ");}
        System.out.println();}
           ///////////perceptron
           //////////////////If and,or,nand,and is selected we chose perceptron
       if(b1.isSelected()||b2.isSelected()||b3.isSelected()||b4.isSelected()){ 
              nn.Perceptron_initialization();
            int i=0;  
       String s="Epoch";
       int num_epoch=1;
       double error;
       double mse;
       ////while => until counter reach max epoch
       while(num_epoch!=1+Integer.parseInt(t1.getText())){
            System.out.println(s+" "+num_epoch);
            mse=0;
            ////////////4 itrations 
      for(int j=0;j<4;j++){
      error=nn.Perceptron(matlogic[j][i],matlogic[j][i+1],matlogic[j][i+2],Double.parseDouble(t2.getText()));
            System.out.println("X1:"+matlogic[j][i]+" "+"X2:"+matlogic[j][i+1]+" "+"Yd:"+matlogic[j][i+2]);
      double power=Math.pow(error,2.0);
      mse+=power;
       }
      ////////find best MSE if pc didn't learned
      mse=mse/4;
      if(mse<=bmse){
      bmse=mse;
      bepoch=num_epoch;
      }
       ////////check if mse =0
      if(mse==0)
          break;
                 drawline();
           try {
               Thread.sleep(250);
           } catch (InterruptedException ex) {
               Logger.getLogger(Front.class.getName()).log(Level.SEVERE, null, ex);
           }
      num_epoch++;
      
       }
        l1.setText(bmse+"");
       l2.setText((int)bepoch+"");
       ///////////change table
       if(b1.isSelected()){
          icon=new ImageIcon(getClass().getResource("/Icons/and.png"));
          jLabel16.setIcon(icon);}
       if(b2.isSelected()){
          icon=new ImageIcon(getClass().getResource("/Icons/or.png"));
          jLabel16.setIcon(icon);}
       if(b3.isSelected()){
          icon=new ImageIcon(getClass().getResource("/Icons/nand.png"));
          jLabel16.setIcon(icon);}
       if(b4.isSelected()){
          icon=new ImageIcon(getClass().getResource("/Icons/nor.png"));
          jLabel16.setIcon(icon);}
       }
       ////////////////////////multi layer
       //////////////////If and,or,nand,and is selected we chose perceptron
       if(b5.isSelected()||b6.isSelected()){ 
           nn.Multilayer_initialization();
        int i=0;  
       String s="Epoch";
       int num_epoch=1;
       double error;
       double mse;
       ////while => until counter reach max epoch
       while(num_epoch!=1+Integer.parseInt(t1.getText())){
            System.out.println(s+" "+num_epoch);
            mse=0;
      for(int j=0;j<4;j++){
      error=nn.multilayer(matlogic[j][i],matlogic[j][i+1],matlogic[j][i+2],Double.parseDouble(t2.getText()));
            System.out.println("X1:"+matlogic[j][i]+" "+"X2:"+matlogic[j][i+1]+" "+"Yd:"+matlogic[j][i+2]);
      double power=Math.pow(error,2.0);
      mse+=power;
       }
     mse=mse/4;
         if(mse<=bmse){
      bmse=mse;
      bepoch=num_epoch;
      }
      System.out.println("mse "+Double.parseDouble(d.format(mse)));
         if(mse<=0.001){
          break;
         }
           drawline();
    
      num_epoch++;
      
       }
       l1.setText(bmse+"");
       l2.setText((int)bepoch+"");
       if(b5.isSelected()){
          icon=new ImageIcon(getClass().getResource("/Icons/xor.png"));
          jLabel16.setIcon(icon);}
       if(b6.isSelected()){
          icon=new ImageIcon(getClass().getResource("/Icons/xnor.png"));
          jLabel16.setIcon(icon);}
       }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed
  public void drawline(){
  if(b1.isSelected()){ 
        jPanel1.getGraphics().clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        Graphics g=jPanel1.getGraphics();
        g.drawLine(0, 400, 600,400);
        g.drawLine(100, 0, 100,500);
        g.setColor(new Color(102,153,255));
        g.drawOval(90, 190, 20,20);
        g.drawOval(90, 390, 20,20);
        g.drawOval(290, 390, 20,20);
        g.fillOval(290, 190, 20,20);
                  g.setColor(Color.RED);
         double xcenter=100,ycenter=400;
         double y1  =(0+((-1*(nn.threshold))/nn.w2))*200;
         double x2=(-((-1*(nn.threshold))/nn.w2))/(-1*(nn.w1)/nn.w2)*200;
        g.drawLine(0, (int)(ycenter-y1)-100,(int)(x2+xcenter)+100,(int)(100+ycenter));


        }
          
        if(b2.isSelected()){
        jPanel1.getGraphics().clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        Graphics g=jPanel1.getGraphics();
        g.drawLine(0, 400, 600,400);
        g.drawLine(100, 0, 100,500);
        g.setColor(new Color(102,153,255));
        g.fillOval(90, 190, 20,20);
        g.drawOval(90, 390, 20,20);
        g.fillOval(290, 390, 20,20);
        g.fillOval(290, 190, 20,20);
                  g.setColor(Color.RED);
         double xcenter=100,ycenter=400;
         double y1  =(0+((-1*(nn.threshold))/nn.w2))*200;
         double x2=(-((-1*(nn.threshold))/nn.w2))/(-1*(nn.w1)/nn.w2)*200;
        g.drawLine(0, (int)(ycenter-y1)-100,(int)(x2+xcenter)+100,(int)(100+ycenter));
        }
           
        if(b3.isSelected()){
        jPanel1.getGraphics().clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        Graphics g=jPanel1.getGraphics();
        g.drawLine(0, 400, 600,400);
        g.drawLine(100, 0, 100,500);
        g.setColor(new Color(102,153,255));
        g.fillOval(90, 190, 20,20);
        g.fillOval(90, 390, 20,20);
        g.fillOval(290, 390, 20,20);
        g.drawOval(290, 190, 20,20);
                  g.setColor(Color.RED);
         double xcenter=100,ycenter=400;
         double y1  =(0+((-1*(nn.threshold))/nn.w2))*200;
         double x2=(-((-1*(nn.threshold))/nn.w2))/(-1*(nn.w1)/nn.w2)*200;
        g.drawLine(0, (int)(ycenter-y1)-100,(int)(x2+xcenter)+100,(int)(100+ycenter));}
           
        if(b4.isSelected()){
        jPanel1.getGraphics().clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        Graphics g=jPanel1.getGraphics();
        g.drawLine(0, 400, 600,400);
        g.drawLine(100, 0, 100,500);
        g.setColor(new Color(102,153,255));
        g.drawOval(90, 190, 20,20);
        g.fillOval(90, 390, 20,20);
        g.drawOval(290, 390, 20,20);
        g.drawOval(290, 190, 20,20);
                  g.setColor(Color.RED);
         double xcenter=100,ycenter=400;
         double y1  =(0+((-1*(nn.threshold))/nn.w2))*200;
         double x2=(-((-1*(nn.threshold))/nn.w2))/(-1*(nn.w1)/nn.w2)*200;
        g.drawLine(0, (int)(ycenter-y1)-100,(int)(x2+xcenter)+100,(int)(100+ycenter));}
           
        if(b5.isSelected()){
        jPanel1.getGraphics().clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        Graphics g=jPanel1.getGraphics();
        g.drawLine(0, 400, 600,400);
        g.drawLine(100, 0, 100,500);
        g.setColor(new Color(102,153,255));
        g.fillOval(90, 190, 20,20);
        g.drawOval(90, 390, 20,20);
        g.fillOval(290, 390, 20,20);
        g.drawOval(290, 190, 20,20);
                  g.setColor(Color.RED);
            double xcenter=100,ycenter=400;
         double y1  =((((nn.threshold3))/nn.w21))*200;
         double x2=(-(((nn.threshold3))/nn.w21))/(-1*(nn.w11)/nn.w21)*200;
       g.drawLine(0, (int)(ycenter-y1)-100,(int)(x2+xcenter)+100,(int)(100+ycenter));
         y1  =(0+(((nn.threshold4))/nn.w22))*200;
         x2=(-(((nn.threshold4))/nn.w22))/(-1*(nn.w12)/nn.w22)*200;
        g.drawLine(0, (int)(ycenter-y1)-100,(int)(x2+xcenter)+100,(int)(100+ycenter));
        }
            
        if(b6.isSelected()){
        jPanel1.getGraphics().clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        Graphics g=jPanel1.getGraphics();
        g.drawLine(0, 400, 600,400);
        g.drawLine(100, 0, 100,500);
        g.setColor(new Color(102,153,255));
        g.drawOval(90, 190, 20,20);
        g.fillOval(90, 390, 20,20);
        g.drawOval(290, 390, 20,20);
        g.fillOval(290, 190, 20,20);
        g.setColor(Color.RED);
              double xcenter=100,ycenter=400;
         double y1  =(0+(((nn.threshold3))/nn.w21))*200;
         double x2=(-(((nn.threshold3))/nn.w21))/(-1*(nn.w11)/nn.w21)*200;
       g.drawLine(0, (int)(ycenter-y1)-100,(int)(x2+xcenter)+100,(int)(100+ycenter));
         y1  =(0+(((nn.threshold4))/nn.w22))*200;
         x2=(-(((nn.threshold4))/nn.w22))/(-1*(nn.w12)/nn.w22)*200;
        g.drawLine(0, (int)(ycenter-y1)-100,(int)(x2+xcenter)+100,(int)(100+ycenter));
        
        }
  
  
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b5;
    private javax.swing.JRadioButton b6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    public javax.swing.JTextField t3;
    public javax.swing.JTextField t4;
    public javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
